# filepath: .pre-commit-config.yaml
repos:
  - repo: https://github.com/pycqa/flake8
    rev: "7.1.1"
    hooks:
      - id: flake8
        additional_dependencies: [Flake8-pyproject]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.15.0"
    hooks:
      - id: mypy
        exclude: build_helpers
        additional_dependencies:
          - types-cachetools==5.5.0.20240820
          - types-filelock==3.2.7
          - types-requests==2.32.0.20241016
          - types-tabulate==0.9.0.20241207
          - types-python-dateutil==2.9.0.20241206
          - SQLAlchemy==2.0.38

  - repo: https://github.com/stefmolin/exif-stripper
    rev: 0.6.1
    hooks:
      - id: strip-exif

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

  - repo: https://github.com/pycqa/isort
    rev: "6.0.0"
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.9.6'
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy

  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: |
            (?x)^(
                tests/.*|
                .*\.svg|
                .*\.yml|
                .*\.json
            )$
      - id: mixed-line-ending
      - id: debug-statements
      - id: check-ast
      - id: trailing-whitespace
        exclude: |
          (?x)^(
                .*\.md
            )$
      - id: check-added-large-files
      - id: check-yaml
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: update-documentation
        name: Update Documentation
        entry: python scripts/update_docs.py
        language: python
        files: ^(frontend/|src/|tests/)
      - id: update-docs
        name: Update Documentation
        entry: python scripts/update_docs.py
        language: system
        pass_filenames: false
        always_run: true