services:
  freqtrade:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: freqtrade
    ports:
      - "8080:8080"  # API port
      - "9999:9999"  # WebUI port (optional)
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./src:/freqtrade/src"
      - "./src/quantum:/freqtrade/user_data/strategies/quantum"
      - "./src/core:/freqtrade/user_data/strategies/core"
      - "./models:/freqtrade/models"
      - "./data:/freqtrade/data"
    environment:
      - PYTHONPATH=/freqtrade/src:/freqtrade/user_data/strategies
    command: >
      trade
      --strategy QuantumHybridStrategy
      --config /freqtrade/user_data/config.json
      --db-url sqlite:///data/tradesv3.sqlite
