services:
  freqtrade:
    image: freqtradeorg/freqtrade:develop_freqai
    container_name: freqtrade
    restart: unless-stopped
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./models:/freqtrade/models"
    ports:
      - "8080:8080"
      - "9999:9999"
    command: >
      trade
      --strategy QuantumHybridStrategy
      --config /freqtrade/user_data/config.json
      --freqaimodel LightGBMRegressor
