version: '3'
services:
  freqtrade:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: freqtrade
    ports:
      - "8080:8080"
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./src:/freqtrade/src"
      - "./models:/freqtrade/models"
      - "./dependencies:/freqtrade/dependencies"
      - "./data:/freqtrade/data"
      # Mount pip cache directory to persist packages
      - "pip-cache:/root/.cache/pip"
    environment:
      - PYTHONPATH=/freqtrade/src:/freqtrade/user_data/strategies
    command: >
      trade
      --strategy QuantumHybridStrategy
      --config /freqtrade/user_data/config.json
    entrypoint: >
      /bin/sh -c "
      python -c 'from src.core.dependency_manager import DependencyManager; DependencyManager().ensure_dependencies()' &&
      freqtrade trade --strategy QuantumHybridStrategy --config /freqtrade/user_data/config.json"

volumes:
  pip-cache:
    driver: local
