version: '3.9'

services:
  freqtrade:
    container_name: freqtrade
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    volumes:
      - "./:/freqtrade/user_data/"
      - "./config.json:/freqtrade/config.json"
      - "./freqai_config.json:/freqtrade/freqai_config.json"
      - "./strategies:/freqtrade/user_data/strategies"
      - "./models:/freqtrade/user_data/models"
      - "./databases:/freqtrade/user_data/databases"
    ports:
      - "8080:8080"
    command: >
      trade
      --strategy QuantumLoopStrategy
      --db-url sqlite:///databases/tradesv3.sqlite
      --logfile /freqtrade/user_data/logs/freqtrade.log
    environment:
      - FT_SERVER_PORT=8080
      - CUDA_VISIBLE_DEVICES=0  # For GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  freqai:
    build:
      context: .
      dockerfile: Dockerfile.freqai-custom
      target: production
    ports:
      - "8080:8080"
    volumes:
      - ./models:/app/models:ro
      - ./data:/app/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  db:
    image: postgres:14-alpine
    container_name: algotradepro5-db
    environment:
      POSTGRES_USER: algotrade
      POSTGRES_PASSWORD: your_password_here
      POSTGRES_DB: algotrade
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: algotradepro5-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@algotradepro5.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: algotradepro5-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - freqai
    restart: unless-stopped

volumes:
  postgres_data:
