services:
  freqtrade:
    container_name: freqtrade
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    volumes:
      - "./:/freqtrade/user_data/"
      - "./config.json:/freqtrade/config.json"
      - "./freqai_config.json:/freqtrade/freqai_config.json"
      - "./strategies:/freqtrade/user_data/strategies"
      - "./models:/freqtrade/user_data/models"
      - "./databases:/freqtrade/user_data/databases"
    ports:
      - "8080:8080"
    command: >
      trade
      --strategy QuantumLoopStrategy
      --db-url sqlite:///databases/tradesv3.sqlite
      --logfile /freqtrade/user_data/logs/freqtrade.log
    environment:
      - FT_SERVER_PORT=8080
      - CUDA_VISIBLE_DEVICES=0  # For GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  freqai:
    build: 
      context: .
      dockerfile: Dockerfile.freqai
      cache_from:
        - freqai-deps:latest
        - freqai-runtime:latest
    ports:
      - "8002:8001"  # Changed from 8001:8001 to 8002:8001
    volumes:
      - type: bind
        source: ./src
        target: /app/src
        read_only: true
      - type: bind
        source: ./models
        target: /app/models
        read_only: true
      - type: volume
        source: freqai_cache
        target: /app/cache
      - type: volume
        source: freqai_logs
        target: /app/logs
    environment:
      - PYTHONPATH=/app
      - MODEL_DIR=/app/models
      - CACHE_DIR=/app/cache
      - DOCKER_BUILDKIT=1
    container_name: freqai
    restart: unless-stopped
    networks:
      - algo_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  db:
    image: postgres:14-alpine
    container_name: algotradepro5-db
    environment:
      POSTGRES_USER: algotrade
      POSTGRES_PASSWORD: "${DB_PASSWORD:-trading_secure_password}"
      POSTGRES_DB: algotrade
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: algotradepro5-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_EMAIL:-admin@algotradepro5.com}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD:-admin}"
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: algotradepro5-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_FREQAI_URL=http://freqai:8001
    depends_on:
      - freqai
    networks:
      - algo_network
    restart: unless-stopped

volumes:
  postgres_data:
  freqai_cache:
    name: freqai_cache
  freqai_logs:
    name: freqai_logs

networks:
  algo_network:
    driver: bridge
