version: '3.8'
services:
  freqtrade:
    container_name: freqtrade
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./config.json:/freqtrade/config.json"
      - "./freqai_config.json:/freqtrade/freqai_config.json"
      - "./models:/freqtrade/models"
      - "./data:/freqtrade/data"
    ports:
      - "127.0.0.1:8080:8080"
    command: trade --config /freqtrade/config.json --strategy QuantumHybridStrategy
    environment:
      - FT_SERVER_PORT=8080
      - CUDA_VISIBLE_DEVICES=0  # For GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  freqai:
    build:
      context: .
      dockerfile: Dockerfile.freqai-custom
    container_name: freqai
    volumes:
      - "./models:/app/models"
      - "./data:/app/data"
      - "C:/AlgoTradPro5/models:/models"  # Map external models directory
    environment:
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  db:
    image: postgres:14
    container_name: algotradedb
    environment:
      - POSTGRES_USER=algotrader
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=algotradedb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: algotrade_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production
      - API_URL=http://freqtrade:8080

volumes:
  pgdata:
