version: '3.8'
services:
  freqtrade:
    container_name: freqtrade
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./config.json:/freqtrade/config.json"
    ports:
      - "127.0.0.1:8080:8080"
    command: trade --config /freqtrade/config.json --strategy QuantumHybridStrategy
    environment:
      - FT_SERVER_PORT=8080
