name: algotrade5
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - scikit-learn
  - pytorch
  - transformers
  - sqlalchemy
  - pytest
  - pip:
    - freqtrade
    - freqai
    - apprise
