from enum import Enum


# REMOVED_UNUSED_CODE: class BacktestState(Enum):
# REMOVED_UNUSED_CODE:     """
# REMOVED_UNUSED_CODE:     Bot application states
# REMOVED_UNUSED_CODE:     """
# REMOVED_UNUSED_CODE: 
# REMOVED_UNUSED_CODE: # REMOVED_UNUSED_CODE:     STARTUP = 1
# REMOVED_UNUSED_CODE: # REMOVED_UNUSED_CODE:     DATALOAD = 2
# REMOVED_UNUSED_CODE: # REMOVED_UNUSED_CODE:     ANALYZE = 3
# REMOVED_UNUSED_CODE: # REMOVED_UNUSED_CODE:     CONVERT = 4
# REMOVED_UNUSED_CODE: # REMOVED_UNUSED_CODE:     BACKTEST = 5
# REMOVED_UNUSED_CODE: 
# REMOVED_UNUSED_CODE:     def __str__(self):
# REMOVED_UNUSED_CODE:         return f"{self.name.lower()}"
