#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Install Pre-commit Hook for AlgoTradePro5.

This script installs the pre-commit hook into the .git/hooks directory
to ensure it runs automatically when committing changes.
"""

import os
import sys
import stat
import shutil
from pathlib import Path

def get_repo_root():
    """Get the root directory of the Git repository."""
    # Walk up the directory tree until we find .git
    current_dir = os.path.abspath(os.path.dirname(__file__))
    while current_dir != os.path.dirname(current_dir):  # Stop at the root directory
        if os.path.exists(os.path.join(current_dir, ".git")):
            return current_dir
        current_dir = os.path.dirname(current_dir)
    
    print("Error: Not in a Git repository")
    sys.exit(1)

def create_hook_script(hooks_dir, batch_path):
    """Create the pre-commit hook script."""
    hook_path = os.path.join(hooks_dir, "pre-commit")
    
    # Create hook content - direct call to the batch file for Windows
    hook_content = f"""#!/bin/sh
# AlgoTradePro5 pre-commit hook
# This file was automatically generated by install_hook.py

# Run the batch file that handles the pre-commit hook
"{batch_path}"
"""
    
    # Write the hook script
    with open(hook_path, 'w') as f:
        f.write(hook_content)
    
    # Make the hook executable
    os.chmod(hook_path, os.stat(hook_path).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    
    return hook_path

def backup_existing_hook(hooks_dir):
    """Backup any existing pre-commit hook."""
    hook_path = os.path.join(hooks_dir, "pre-commit")
    backup_path = os.path.join(hooks_dir, "pre-commit.backup")
    
    if os.path.exists(hook_path):
        shutil.copy2(hook_path, backup_path)
        print(f"Backed up existing pre-commit hook to {backup_path}")

def main():
    """Main entry point for the hook installer."""
    # Get the repository root
    repo_root = get_repo_root()
    
    # Path to the hooks directory
    hooks_dir = os.path.join(repo_root, ".git", "hooks")
    
    # Create hooks directory if it doesn't exist
    os.makedirs(hooks_dir, exist_ok=True)
    
    # Backup existing hook if it exists
    backup_existing_hook(hooks_dir)
    
    # Path to the batch file
    batch_path = os.path.join(repo_root, "src", "hooks", "pre_commit.bat")
    batch_abs_path = os.path.abspath(batch_path)
    
    # Create the pre-commit hook script
    hook_path = create_hook_script(hooks_dir, batch_abs_path)
    
    print(f"Pre-commit hook installed successfully at {hook_path}")
    print("The hook will run automatically when you commit changes.")
    print("It will use the batch file at:", batch_abs_path)

if __name__ == "__main__":
    main()