#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Install pre-commit hook for AlgoTradePro5.

This script installs the pre-commit hook into the .git/hooks directory.
"""

import os
# REMOVED_UNUSED_CODE: import shutil
import stat
import subprocess
import sys
# REMOVED_UNUSED_CODE: from pathlib import Path


def get_repo_root():
    """Get the root directory of the Git repository."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError:
        print("Error: Not in a Git repository")
        sys.exit(1)

def create_hook_script(hooks_dir, source_script):
    """Create the pre-commit hook script."""
    hook_path = os.path.join(hooks_dir, "pre-commit")
    
    # Create hook content that calls our Python script
    hook_content = f"""#!/bin/sh
# Pre-commit hook for AlgoTradePro5
# Auto-generated by install_pre_commit.py

# Run the Python pre-commit hook script
python "{source_script}" "$@"
"""
    
    # Write the hook script
    with open(hook_path, 'w') as f:
        f.write(hook_content)
    
    # Make the hook executable
    os.chmod(hook_path, os.stat(hook_path).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    
    return hook_path

def main():
    """Main function to install the pre-commit hook."""
    # Get the repository root
    repo_root = get_repo_root()
    
    # Path to the hooks directory
    hooks_dir = os.path.join(repo_root, ".git", "hooks")
    
    # Create hooks directory if it doesn't exist
    os.makedirs(hooks_dir, exist_ok=True)
    
    # Path to the pre-commit hook script
    source_script = os.path.join(repo_root, "src", "pre_commit_hook.py")
    
    # Check if the pre-commit hook script exists
    if not os.path.exists(source_script):
        print(f"Error: Pre-commit hook script not found at {source_script}")
        sys.exit(1)
    
    # Create the hook script
    hook_path = create_hook_script(hooks_dir, source_script)
    
    print(f"Pre-commit hook installed at {hook_path}")
    print("The hook will run automatically before each commit.")

if __name__ == "__main__":
    main()