name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature-branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Install Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t algotradepro5 .

    - name: Run Docker container
      run: |
        docker run algotradepro5

    - name: Run GitHub Copilot Fixes
      run: ./scripts/copilot_fix.sh

    - name: Commit and push documentation updates
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs/journal.md docs/integration-guide.md docs/architecture-analysis.md
        git commit -m "Automated documentation update"
        git push